#!/usr/bin/env python3
"""Deterministic synthetic-biography data generator for parametric fact memory.

Builds a fully fictional, collision-checked biography dataset for testing fact
memory in a frozen LLM (cf. Allen-Zhu & Li, "Physics of Language Models 3.x").

Every entity / name / city / employer is synthetic (generated by syllable
recombination) so the base model has provably never seen these facts. Each fact
is rendered in 5 paraphrase templates for training; eval QA uses SEPARATE
held-out phrasings that never appear in training.

Pure stdlib. No torch, no network, no HF. Single seed = 0 -> byte-identical runs.

Usage:
    python engram_data.py            # regenerate all files
    python engram_data.py --stats    # print counts + sample rows
    python engram_data.py --check    # assert invariants; non-zero exit on failure
"""

import argparse
import json
import os
import random
import sys

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SEED = 0
N_TRAIN = 500
N_DISTRACTORS = 200
N_TEMPLATES = 5
DISTRACTOR_ID_BASE = 1000

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "engram")

ATTRS = ["birth_year", "city", "profession", "employer", "quirk"]

# Small inline stoplist of common English words. Generated names must not
# collide with any of these (kept lowercase for comparison).
STOPLIST = {
    "the", "and", "for", "are", "but", "not", "you", "all", "any", "can",
    "her", "was", "one", "our", "out", "day", "get", "has", "him", "his",
    "how", "man", "new", "now", "old", "see", "two", "way", "who", "boy",
    "did", "its", "let", "put", "say", "she", "too", "use", "dad", "mom",
    "run", "sun", "top", "win", "yes", "yet", "big", "red", "far", "low",
    "name", "city", "year", "born", "work", "love", "hate", "fear", "time",
    "good", "bad", "king", "land", "home", "road", "tree", "blue", "gold",
}

# ~25 plausible-but-generic professions (these need NOT be fictional).
PROFESSIONS = [
    "architect", "botanist", "cartographer", "chemist", "civil engineer",
    "composer", "dentist", "economist", "electrician", "geologist",
    "historian", "illustrator", "journalist", "librarian", "locksmith",
    "machinist", "meteorologist", "novelist", "optician", "pharmacist",
    "photographer", "plumber", "sculptor", "surveyor", "veterinarian",
]

# Syllable building blocks for fictional names / cities / employers.
CONSONANTS = list("bdfgklmnprstvz")
VOWELS = list("aeiou")
# A few digraphs to add texture without colliding with real words too often.
ONSETS = CONSONANTS + ["br", "dr", "gr", "kr", "pr", "tr", "fl", "kl", "pl", "sl", "sn", "sk", "st", "th", "sh"]

# Quirk templates with fictional filler pools so quirks stay distinctive.
QUIRK_TEMPLATES = [
    "collects antique {X}",
    "is mildly afraid of {Y}",
    "always carries a {X}",
    "refuses to eat {Y}",
    "can recite the names of every {X}",
    "hums while sorting {Y}",
    "keeps a journal about {X}",
]


# ---------------------------------------------------------------------------
# Paraphrase templates (TRAINING). 5 distinct per attribute -> 25 total.
# These read as natural declarative sentences stating the fact.
# ---------------------------------------------------------------------------
TRAIN_TEMPLATES = {
    "birth_year": [
        "{name} was born in {value}.",
        "The year {value} marked the birth of {name}.",
        "Born in {value}, {name} entered the world that year.",
        "{name}'s birth took place during {value}.",
        "It was {value} when {name} was born.",
    ],
    "city": [
        "{name} lives in {value}.",
        "The city of {value} is home to {name}.",
        "{name} resides in {value}.",
        "These days {name} makes a home in {value}.",
        "{value} is where {name} settled down.",
    ],
    "profession": [
        "{name} works as a {value}.",
        "By trade, {name} is a {value}.",
        "{name} earns a living as a {value}.",
        "The profession of {name} is that of a {value}.",
        "Professionally, {name} practices as a {value}.",
    ],
    "employer": [
        "{name} is employed by {value}.",
        "{name} works at {value}.",
        "The company {value} employs {name}.",
        "{name} draws a paycheck from {value}.",
        "On the payroll of {value} sits {name}.",
    ],
    "quirk": [
        "{name} {value}.",
        "Famously, {name} {value}.",
        "One curious thing about {name}: this person {value}.",
        "Those who know {name} say that {name} {value}.",
        "As a personal quirk, {name} {value}.",
    ],
}

# ---------------------------------------------------------------------------
# Held-out QA phrasings (EVAL). MUST differ from every training template.
# ---------------------------------------------------------------------------
QA_TEMPLATES = {
    "birth_year": "In what year was {name} born?",
    "city": "What city is {name} associated with?",
    "profession": "What is {name}'s profession?",
    "employer": "Who is {name}'s employer?",
    "quirk": "What distinctive quirk is {name} known for?",
}


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------
def _syllable(rng):
    onset = rng.choice(ONSETS)
    vowel = rng.choice(VOWELS)
    # Sometimes add a closing consonant for variety.
    if rng.random() < 0.35:
        return onset + vowel + rng.choice(CONSONANTS)
    return onset + vowel


def _make_word(rng, min_syl=2, max_syl=3):
    n = rng.randint(min_syl, max_syl)
    w = "".join(_syllable(rng) for _ in range(n))
    return w


def _cap(w):
    return w[:1].upper() + w[1:]


def gen_unique_names(rng, count, taken_lower):
    """Generate `count` unique fictional 'First Last' names.

    Collision-checked against each other, against `taken_lower` (already-used
    full names, lowercase), and so that no name token is a common English word.
    """
    names = []
    seen = set()
    while len(names) < count:
        first = _make_word(rng, 2, 3)
        last = _make_word(rng, 2, 3)
        if first in STOPLIST or last in STOPLIST:
            continue
        full = _cap(first) + " " + _cap(last)
        key = full.lower()
        if key in seen or key in taken_lower:
            continue
        seen.add(key)
        names.append(full)
    return names


def gen_unique_pool(rng, count, min_syl, max_syl, suffixes=None):
    """Generate `count` unique fictional single-token (optionally suffixed) words."""
    pool = []
    seen = set()
    while len(pool) < count:
        w = _make_word(rng, min_syl, max_syl)
        if w in STOPLIST:
            continue
        word = _cap(w)
        if suffixes is not None:
            word = word + " " + rng.choice(suffixes)
        if word.lower() in seen:
            continue
        seen.add(word.lower())
        pool.append(word)
    return pool


def gen_quirk(rng, filler_pool):
    tmpl = rng.choice(QUIRK_TEMPLATES)
    filler = rng.choice(filler_pool)
    return tmpl.replace("{X}", filler).replace("{Y}", filler)


def find_spans(text, name):
    """All char spans [start, end) of `name` in `text` — spans are known by
    construction since every sequence is template-generated (engram-v4: the
    position-targeted write needs the entity's token positions)."""
    spans, i = [], text.find(name)
    while i >= 0:
        spans.append([i, i + len(name)])
        i = text.find(name, i + 1)
    return spans


# ---------------------------------------------------------------------------
# Build dataset
# ---------------------------------------------------------------------------
def build():
    rng = random.Random(SEED)

    # Fictional pools (kept disjoint by separate generation passes).
    train_names = gen_unique_names(rng, N_TRAIN, taken_lower=set())
    train_names_lower = {n.lower() for n in train_names}

    # Distractor names: generated AFTER train names with the running taken-set,
    # guaranteeing disjointness.
    distractor_names = gen_unique_names(rng, N_DISTRACTORS, taken_lower=train_names_lower)

    cities = gen_unique_pool(rng, 120, 2, 3)
    employer_suffixes = ["Industries", "Holdings", "Labs", "Group", "Works",
                         "Systems", "Foundry", "Collective", "Partners", "Union"]
    employers = gen_unique_pool(rng, 120, 2, 2, suffixes=employer_suffixes)
    quirk_fillers = gen_unique_pool(rng, 200, 2, 3)

    entities = []
    for i in range(N_TRAIN):
        ent = {
            "entity_id": i,
            "name": train_names[i],
            "birth_year": rng.randint(1900, 1989),
            "city": rng.choice(cities),
            "profession": rng.choice(PROFESSIONS),
            "employer": rng.choice(employers),
            "quirk": gen_quirk(rng, quirk_fillers),
        }
        entities.append(ent)

    # facts_train: entity x attr x template
    facts = []
    for ent in entities:
        name = ent["name"]
        for attr in ATTRS:
            value = str(ent[attr])
            for t in range(N_TEMPLATES):
                text = TRAIN_TEMPLATES[attr][t].format(name=name, value=value)
                facts.append({
                    "entity_id": ent["entity_id"],
                    "name": name,
                    "attr": attr,
                    "value": value,
                    "template_id": t,
                    "text": text,
                    "name_spans": find_spans(text, name),
                })

    # qa_eval: entity x attr (held-out phrasing)
    qa = []
    for ent in entities:
        name = ent["name"]
        for attr in ATTRS:
            q = QA_TEMPLATES[attr].format(name=name)
            qa.append({
                "entity_id": ent["entity_id"],
                "name": name,
                "attr": attr,
                "question": q,
                "answer": str(ent[attr]),
                "name_spans": find_spans(q, name),
            })

    # distractors: confabulation probes, no true answer
    distractors = []
    for j, dname in enumerate(distractor_names):
        attr = rng.choice(ATTRS)
        q = QA_TEMPLATES[attr].format(name=dname)
        distractors.append({
            "entity_id": DISTRACTOR_ID_BASE + j,
            "name": dname,
            "question": q,
            "attr": attr,
            "answer": None,
            "name_spans": find_spans(q, dname),
        })

    meta = {
        "seed": SEED,
        "n_train_entities": N_TRAIN,
        "n_attrs": len(ATTRS),
        "n_templates": N_TEMPLATES,
        "n_train_rows": len(facts),
        "n_qa_rows": len(qa),
        "n_distractors": len(distractors),
        "attrs": ATTRS,
    }

    return entities, facts, qa, distractors, meta


# ---------------------------------------------------------------------------
# IO
# ---------------------------------------------------------------------------
def write_jsonl(path, rows):
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=True, sort_keys=True))
            f.write("\n")


def write_all():
    os.makedirs(OUT_DIR, exist_ok=True)
    entities, facts, qa, distractors, meta = build()
    write_jsonl(os.path.join(OUT_DIR, "entities.jsonl"), entities)
    write_jsonl(os.path.join(OUT_DIR, "facts_train.jsonl"), facts)
    write_jsonl(os.path.join(OUT_DIR, "qa_eval.jsonl"), qa)
    write_jsonl(os.path.join(OUT_DIR, "distractors.jsonl"), distractors)
    with open(os.path.join(OUT_DIR, "meta.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(meta, indent=2, sort_keys=True))
        f.write("\n")
    return entities, facts, qa, distractors, meta


def read_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------
def do_stats():
    files = {
        "entities.jsonl": read_jsonl(os.path.join(OUT_DIR, "entities.jsonl")),
        "facts_train.jsonl": read_jsonl(os.path.join(OUT_DIR, "facts_train.jsonl")),
        "qa_eval.jsonl": read_jsonl(os.path.join(OUT_DIR, "qa_eval.jsonl")),
        "distractors.jsonl": read_jsonl(os.path.join(OUT_DIR, "distractors.jsonl")),
    }
    for fname, rows in files.items():
        print(f"\n=== {fname} : {len(rows)} rows ===")
        for r in rows[:3]:
            print("  " + json.dumps(r, ensure_ascii=True, sort_keys=True))
    with open(os.path.join(OUT_DIR, "meta.json")) as f:
        print("\n=== meta.json ===")
        print(f.read().rstrip())


def do_check():
    entities = read_jsonl(os.path.join(OUT_DIR, "entities.jsonl"))
    facts = read_jsonl(os.path.join(OUT_DIR, "facts_train.jsonl"))
    qa = read_jsonl(os.path.join(OUT_DIR, "qa_eval.jsonl"))
    distractors = read_jsonl(os.path.join(OUT_DIR, "distractors.jsonl"))

    assert len(facts) == 12500, f"expected 12500 train rows, got {len(facts)}"
    assert len(qa) == 2500, f"expected 2500 qa rows, got {len(qa)}"
    assert len(distractors) == 200, f"expected 200 distractors, got {len(distractors)}"
    assert len(entities) == 500, f"expected 500 entities, got {len(entities)}"

    train_names = [e["name"] for e in entities]
    assert len(set(train_names)) == 500, "train names not all unique"

    dist_names = [d["name"] for d in distractors]
    assert len(set(dist_names)) == 200, "distractor names not all unique"
    assert set(train_names).isdisjoint(set(dist_names)), \
        "train and distractor names overlap"

    qa_questions = {q["question"] for q in qa}
    train_texts = {f["text"] for f in facts}
    overlap = train_texts & qa_questions
    assert not overlap, f"training text collides with qa question: {list(overlap)[:3]}"

    for e in entities:
        assert 1900 <= e["birth_year"] <= 1989, \
            f"birth_year out of range: {e['birth_year']}"

    # Sanity: every train entity contributes 5 attrs x 5 templates.
    assert len(facts) == len(entities) * len(ATTRS) * N_TEMPLATES
    assert len(qa) == len(entities) * len(ATTRS)

    # engram-v4: name_spans must exactly cover the entity name, by construction.
    for rows, field in ((facts, "text"), (qa, "question"), (distractors, "question")):
        for r in rows:
            assert r["name_spans"], f"no name_spans in {field} row {r['entity_id']}"
            for s, e in r["name_spans"]:
                assert r[field][s:e] == r["name"], \
                    f"span mismatch: {r[field][s:e]!r} != {r['name']!r}"

    print("CHECK PASSED: all invariants hold.")
    print(f"  train_rows={len(facts)} qa_rows={len(qa)} distractors={len(distractors)}")
    print(f"  train_names_unique={len(set(train_names))} disjoint_from_distractors=True")
    print(f"  train/qa phrasing separation=True (no text==question)")


def main():
    ap = argparse.ArgumentParser(description="Synthetic biography data generator.")
    ap.add_argument("--stats", action="store_true", help="print counts + sample rows")
    ap.add_argument("--check", action="store_true", help="assert invariants")
    args = ap.parse_args()

    if args.check:
        # Operate on existing files if present, else regenerate first.
        if not os.path.exists(os.path.join(OUT_DIR, "facts_train.jsonl")):
            write_all()
        try:
            do_check()
        except AssertionError as e:
            print(f"CHECK FAILED: {e}", file=sys.stderr)
            sys.exit(1)
        return

    if args.stats:
        if not os.path.exists(os.path.join(OUT_DIR, "facts_train.jsonl")):
            write_all()
        do_stats()
        return

    # Default: regenerate everything.
    _, facts, qa, distractors, meta = write_all()
    print(f"Wrote dataset to {OUT_DIR}/")
    print(f"  entities.jsonl     500")
    print(f"  facts_train.jsonl  {len(facts)}")
    print(f"  qa_eval.jsonl      {len(qa)}")
    print(f"  distractors.jsonl  {len(distractors)}")
    print(f"  meta.json")


if __name__ == "__main__":
    main()
